create table if not exists notification_settings (
  id uuid primary key default uuid_generate_v4(),
  entity_id uuid references entities(id),
  user_id uuid references users(id),
  role text,
  whatsapp_number text,
  whatsapp_active boolean default false,
  email text,
  email_active boolean default false,
  freq_orders text default 'each' check (freq_orders in ('each','hourly','daily')),
  freq_stock text default 'realtime' check (freq_stock in ('realtime','daily','off')),
  freq_cash text default 'each' check (freq_cash in ('each','daily','off')),
  daily_summary_time text default '20:00',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table notification_settings enable row level security;

create policy "admin_own_entity_notification_settings" on notification_settings
  for all using (
    auth.uid() in (
      select id from users where role in ('super_admin','admin') and (entity_id = notification_settings.entity_id or role = 'super_admin')
    )
  );

insert into permissions (role, action, resource, enabled) values
  ('super_admin','view','products',true),
  ('super_admin','create','products',true),
  ('super_admin','edit','products',true),
  ('super_admin','delete','products',true),
  ('super_admin','export','products',true),
  ('super_admin','validate','products',true),
  ('super_admin','notify','products',true),
  ('super_admin','view','stock',true),
  ('super_admin','create','stock',true),
  ('super_admin','edit','stock',true),
  ('super_admin','delete','stock',true),
  ('super_admin','export','stock',true),
  ('super_admin','validate','stock',true),
  ('super_admin','notify','stock',true),
  ('super_admin','view','invoices',true),
  ('super_admin','create','invoices',true),
  ('super_admin','edit','invoices',true),
  ('super_admin','delete','invoices',true),
  ('super_admin','export','invoices',true),
  ('super_admin','validate','invoices',true),
  ('super_admin','notify','invoices',true),
  ('super_admin','view','reports',true),
  ('super_admin','create','reports',true),
  ('super_admin','edit','reports',true),
  ('super_admin','delete','reports',true),
  ('super_admin','export','reports',true),
  ('super_admin','validate','reports',true),
  ('super_admin','notify','reports',true),
  ('super_admin','view','users',true),
  ('super_admin','create','users',true),
  ('super_admin','edit','users',true),
  ('super_admin','delete','users',true),
  ('super_admin','export','users',true),
  ('super_admin','validate','users',true),
  ('super_admin','notify','users',true),
  ('super_admin','view','cash_sessions',true),
  ('super_admin','create','cash_sessions',true),
  ('super_admin','edit','cash_sessions',true),
  ('super_admin','delete','cash_sessions',true),
  ('super_admin','export','cash_sessions',true),
  ('super_admin','validate','cash_sessions',true),
  ('super_admin','notify','cash_sessions',true),
  ('super_admin','view','orders',true),
  ('super_admin','create','orders',true),
  ('super_admin','edit','orders',true),
  ('super_admin','delete','orders',true),
  ('super_admin','export','orders',true),
  ('super_admin','validate','orders',true),
  ('super_admin','notify','orders',true),
  ('super_admin','view','notifications',true),
  ('super_admin','create','notifications',true),
  ('super_admin','edit','notifications',true),
  ('super_admin','delete','notifications',true),
  ('super_admin','export','notifications',true),
  ('super_admin','validate','notifications',true),
  ('super_admin','notify','notifications',true),

  ('admin','view','products',true),
  ('admin','create','products',true),
  ('admin','edit','products',true),
  ('admin','delete','products',true),
  ('admin','export','products',true),
  ('admin','validate','products',true),
  ('admin','notify','products',true),
  ('admin','view','stock',true),
  ('admin','create','stock',true),
  ('admin','edit','stock',true),
  ('admin','delete','stock',false),
  ('admin','export','stock',true),
  ('admin','validate','stock',true),
  ('admin','notify','stock',true),
  ('admin','view','invoices',true),
  ('admin','create','invoices',true),
  ('admin','edit','invoices',true),
  ('admin','delete','invoices',false),
  ('admin','export','invoices',true),
  ('admin','validate','invoices',true),
  ('admin','notify','invoices',true),
  ('admin','view','reports',true),
  ('admin','create','reports',true),
  ('admin','edit','reports',false),
  ('admin','delete','reports',false),
  ('admin','export','reports',true),
  ('admin','validate','reports',false),
  ('admin','notify','reports',true),
  ('admin','view','users',true),
  ('admin','create','users',true),
  ('admin','edit','users',true),
  ('admin','delete','users',false),
  ('admin','export','users',true),
  ('admin','validate','users',false),
  ('admin','notify','users',true),
  ('admin','view','cash_sessions',true),
  ('admin','create','cash_sessions',false),
  ('admin','edit','cash_sessions',false),
  ('admin','delete','cash_sessions',false),
  ('admin','export','cash_sessions',true),
  ('admin','validate','cash_sessions',true),
  ('admin','notify','cash_sessions',true),
  ('admin','view','orders',true),
  ('admin','create','orders',true),
  ('admin','edit','orders',true),
  ('admin','delete','orders',false),
  ('admin','export','orders',true),
  ('admin','validate','orders',true),
  ('admin','notify','orders',true),
  ('admin','view','notifications',true),
  ('admin','create','notifications',true),
  ('admin','edit','notifications',false),
  ('admin','delete','notifications',false),
  ('admin','export','notifications',false),
  ('admin','validate','notifications',false),
  ('admin','notify','notifications',true),

  ('manager','view','products',true),
  ('manager','create','products',false),
  ('manager','edit','products',true),
  ('manager','delete','products',false),
  ('manager','export','products',true),
  ('manager','validate','products',false),
  ('manager','notify','products',false),
  ('manager','view','stock',true),
  ('manager','create','stock',true),
  ('manager','edit','stock',true),
  ('manager','delete','stock',false),
  ('manager','export','stock',true),
  ('manager','validate','stock',false),
  ('manager','notify','stock',true),
  ('manager','view','invoices',true),
  ('manager','create','invoices',true),
  ('manager','edit','invoices',true),
  ('manager','delete','invoices',false),
  ('manager','export','invoices',true),
  ('manager','validate','invoices',true),
  ('manager','notify','invoices',false),
  ('manager','view','reports',true),
  ('manager','create','reports',false),
  ('manager','edit','reports',false),
  ('manager','delete','reports',false),
  ('manager','export','reports',true),
  ('manager','validate','reports',false),
  ('manager','notify','reports',false),
  ('manager','view','users',false),
  ('manager','create','users',false),
  ('manager','edit','users',false),
  ('manager','delete','users',false),
  ('manager','export','users',false),
  ('manager','validate','users',false),
  ('manager','notify','users',false),
  ('manager','view','cash_sessions',true),
  ('manager','create','cash_sessions',false),
  ('manager','edit','cash_sessions',false),
  ('manager','delete','cash_sessions',false),
  ('manager','export','cash_sessions',true),
  ('manager','validate','cash_sessions',false),
  ('manager','notify','cash_sessions',false),
  ('manager','view','orders',true),
  ('manager','create','orders',true),
  ('manager','edit','orders',true),
  ('manager','delete','orders',false),
  ('manager','export','orders',true),
  ('manager','validate','orders',true),
  ('manager','notify','orders',false),
  ('manager','view','notifications',true),
  ('manager','create','notifications',false),
  ('manager','edit','notifications',false),
  ('manager','delete','notifications',false),
  ('manager','export','notifications',false),
  ('manager','validate','notifications',false),
  ('manager','notify','notifications',false),

  ('vendeur','view','products',true),
  ('vendeur','create','products',false),
  ('vendeur','edit','products',false),
  ('vendeur','delete','products',false),
  ('vendeur','export','products',false),
  ('vendeur','validate','products',false),
  ('vendeur','notify','products',false),
  ('vendeur','view','stock',true),
  ('vendeur','create','stock',false),
  ('vendeur','edit','stock',false),
  ('vendeur','delete','stock',false),
  ('vendeur','export','stock',false),
  ('vendeur','validate','stock',false),
  ('vendeur','notify','stock',false),
  ('vendeur','view','invoices',true),
  ('vendeur','create','invoices',true),
  ('vendeur','edit','invoices',false),
  ('vendeur','delete','invoices',false),
  ('vendeur','export','invoices',false),
  ('vendeur','validate','invoices',false),
  ('vendeur','notify','invoices',false),
  ('vendeur','view','reports',false),
  ('vendeur','create','reports',false),
  ('vendeur','edit','reports',false),
  ('vendeur','delete','reports',false),
  ('vendeur','export','reports',false),
  ('vendeur','validate','reports',false),
  ('vendeur','notify','reports',false),
  ('vendeur','view','users',false),
  ('vendeur','create','users',false),
  ('vendeur','edit','users',false),
  ('vendeur','delete','users',false),
  ('vendeur','export','users',false),
  ('vendeur','validate','users',false),
  ('vendeur','notify','users',false),
  ('vendeur','view','cash_sessions',false),
  ('vendeur','create','cash_sessions',false),
  ('vendeur','edit','cash_sessions',false),
  ('vendeur','delete','cash_sessions',false),
  ('vendeur','export','cash_sessions',false),
  ('vendeur','validate','cash_sessions',false),
  ('vendeur','notify','cash_sessions',false),
  ('vendeur','view','orders',true),
  ('vendeur','create','orders',true),
  ('vendeur','edit','orders',false),
  ('vendeur','delete','orders',false),
  ('vendeur','export','orders',false),
  ('vendeur','validate','orders',false),
  ('vendeur','notify','orders',false),
  ('vendeur','view','notifications',true),
  ('vendeur','create','notifications',false),
  ('vendeur','edit','notifications',false),
  ('vendeur','delete','notifications',false),
  ('vendeur','export','notifications',false),
  ('vendeur','validate','notifications',false),
  ('vendeur','notify','notifications',false),

  ('caissier','view','products',true),
  ('caissier','create','products',false),
  ('caissier','edit','products',false),
  ('caissier','delete','products',false),
  ('caissier','export','products',false),
  ('caissier','validate','products',false),
  ('caissier','notify','products',false),
  ('caissier','view','stock',false),
  ('caissier','create','stock',false),
  ('caissier','edit','stock',false),
  ('caissier','delete','stock',false),
  ('caissier','export','stock',false),
  ('caissier','validate','stock',false),
  ('caissier','notify','stock',false),
  ('caissier','view','invoices',true),
  ('caissier','create','invoices',true),
  ('caissier','edit','invoices',false),
  ('caissier','delete','invoices',false),
  ('caissier','export','invoices',false),
  ('caissier','validate','invoices',false),
  ('caissier','notify','invoices',false),
  ('caissier','view','reports',false),
  ('caissier','create','reports',false),
  ('caissier','edit','reports',false),
  ('caissier','delete','reports',false),
  ('caissier','export','reports',false),
  ('caissier','validate','reports',false),
  ('caissier','notify','reports',false),
  ('caissier','view','users',false),
  ('caissier','create','users',false),
  ('caissier','edit','users',false),
  ('caissier','delete','users',false),
  ('caissier','export','users',false),
  ('caissier','validate','users',false),
  ('caissier','notify','users',false),
  ('caissier','view','cash_sessions',true),
  ('caissier','create','cash_sessions',true),
  ('caissier','edit','cash_sessions',true),
  ('caissier','delete','cash_sessions',false),
  ('caissier','export','cash_sessions',false),
  ('caissier','validate','cash_sessions',false),
  ('caissier','notify','cash_sessions',false),
  ('caissier','view','orders',false),
  ('caissier','create','orders',false),
  ('caissier','edit','orders',false),
  ('caissier','delete','orders',false),
  ('caissier','export','orders',false),
  ('caissier','validate','orders',false),
  ('caissier','notify','orders',false),
  ('caissier','view','notifications',true),
  ('caissier','create','notifications',false),
  ('caissier','edit','notifications',false),
  ('caissier','delete','notifications',false),
  ('caissier','export','notifications',false),
  ('caissier','validate','notifications',false),
  ('caissier','notify','notifications',false),

  ('readonly','view','products',true),
  ('readonly','create','products',false),
  ('readonly','edit','products',false),
  ('readonly','delete','products',false),
  ('readonly','export','products',false),
  ('readonly','validate','products',false),
  ('readonly','notify','products',false),
  ('readonly','view','stock',true),
  ('readonly','create','stock',false),
  ('readonly','edit','stock',false),
  ('readonly','delete','stock',false),
  ('readonly','export','stock',false),
  ('readonly','validate','stock',false),
  ('readonly','notify','stock',false),
  ('readonly','view','invoices',true),
  ('readonly','create','invoices',false),
  ('readonly','edit','invoices',false),
  ('readonly','delete','invoices',false),
  ('readonly','export','invoices',false),
  ('readonly','validate','invoices',false),
  ('readonly','notify','invoices',false),
  ('readonly','view','reports',true),
  ('readonly','create','reports',false),
  ('readonly','edit','reports',false),
  ('readonly','delete','reports',false),
  ('readonly','export','reports',false),
  ('readonly','validate','reports',false),
  ('readonly','notify','reports',false),
  ('readonly','view','users',false),
  ('readonly','create','users',false),
  ('readonly','edit','users',false),
  ('readonly','delete','users',false),
  ('readonly','export','users',false),
  ('readonly','validate','users',false),
  ('readonly','notify','users',false),
  ('readonly','view','cash_sessions',false),
  ('readonly','create','cash_sessions',false),
  ('readonly','edit','cash_sessions',false),
  ('readonly','delete','cash_sessions',false),
  ('readonly','export','cash_sessions',false),
  ('readonly','validate','cash_sessions',false),
  ('readonly','notify','cash_sessions',false),
  ('readonly','view','orders',true),
  ('readonly','create','orders',false),
  ('readonly','edit','orders',false),
  ('readonly','delete','orders',false),
  ('readonly','export','orders',false),
  ('readonly','validate','orders',false),
  ('readonly','notify','orders',false),
  ('readonly','view','notifications',false),
  ('readonly','create','notifications',false),
  ('readonly','edit','notifications',false),
  ('readonly','delete','notifications',false),
  ('readonly','export','notifications',false),
  ('readonly','validate','notifications',false),
  ('readonly','notify','notifications',false)
on conflict do nothing;

-- Security settings per entity (auth method for cash confirmations)
create table if not exists security_settings (
  id uuid primary key default uuid_generate_v4(),
  entity_id uuid references entities(id) unique,
  auth_method text not null default 'pin' check (auth_method in ('pin','fingerprint','both')),
  session_duration_h int not null default 8,
  max_login_attempts int not null default 5,
  min_password_length int not null default 8,
  require_uppercase boolean default true,
  require_number boolean default true,
  require_special boolean default false,
  updated_at timestamptz default now()
);

alter table security_settings enable row level security;

create policy "super_admin_security_settings" on security_settings
  for all using (auth.uid() in (select id from users where role = 'super_admin'));

create policy "read_own_entity_security_settings" on security_settings
  for select using (auth.uid() in (select id from users where entity_id = security_settings.entity_id));

-- Table paramètres de charte graphique
create table if not exists theme_settings (
  id uuid primary key default uuid_generate_v4(),
  entity_id uuid references entities(id) unique,
  -- Couleurs
  color_primary text not null default '#2C5219',
  color_accent text not null default '#C9881A',
  color_bg text not null default '#FAF7F0',
  color_surface text not null default '#FFFFFF',
  color_text text not null default '#1E3B10',
  color_sidebar text not null default '#1E3B10',
  -- Typographie
  font_heading text not null default 'Cormorant Garamond',
  font_body text not null default 'DM Sans',
  -- UI
  border_radius text not null default 'sharp',
  sidebar_style text not null default 'dark',
  updated_at timestamptz default now()
);

alter table theme_settings enable row level security;
create policy "super_admin_theme" on theme_settings
  for all using (auth.uid() in (select id from users where role = 'super_admin'));
create policy "read_own_theme" on theme_settings
  for select using (auth.uid() in (select id from users where entity_id = theme_settings.entity_id));
